database:
  path: ${SQLITE_DATA_DIR:-./data}/${SQLITE_DB:-sensor_data.db}

tables:
  - name: vibration_data
    columns:
      - name: timestamp
        type: TEXT
      - name: sensor_name
        type: TEXT
      - name: data_type
        type: INTEGER
      - name: json_value
        type: TEXT
